export const environment = {
    production: true,
    canaldeventadefault: '2015000002',
    puntodeventadefault: '2',
    // codigocomercio: '517207314',
    codigocomercio: '302757612',
    pagoefectivoservice: 'https://cip.pagoefectivo.pe/genpagoif.aspx',
    visabuttonservice: 'https://static-content.vnforapps.com/v1/js/checkout.js',
    versioncheckurl: 'https://soatdigital.protectasecurity.pe/version.json',
    //   backendapi: 'https://soatservicios.protectasecurity.pe/RestDigital/api',
    backendapi: 'http://190.216.170.173/RestPRO/api',
    // backendapi: 'http://190.216.170.173/RestDESAMG/api',
    // backendapi: 'http://localhost:2085/api',
    gestorapi: 'https://soatservicios.protectasecurity.pe/WSGestorCliente/Api',
    kunturapi: 'http://190.216.170.173/WSPlataformaPRO/Api',
    // kunturapi: 'http://localhost:30897/Api',
    domainurl: 'https://soatdigital.protectasecurity.pe',
};
